import {useEffect,useRef,useState} from 'react';
import type {Asset,ImageOperations} from '../core/schema';
import {removeConnectedColor} from '../engine/alpha';
import {uploadAsset,browserOnly} from '../app/storage';
import {assetUrl} from '../app/assetUrl';
import {Dialog} from './Dialog';
export function AlphaEditor({asset,jobId,onClose,onApply}:{asset:Asset;jobId:string;onClose:()=>void;onApply:(result:Asset,operation:ImageOperations['backgroundRemove'])=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),original=useRef<ImageData|null>(null);
 const [ready,setReady]=useState(false),[seed,setSeed]=useState<{x:number;y:number}|null>(null),[threshold,setThreshold]=useState(.12),[feather,setFeather]=useState(.03),[color,setColor]=useState('#ffffff'),[error,setError]=useState(''),[saving,setSaving]=useState(false),[dimensions,setDimensions]=useState('');
 useEffect(()=>{let active=true;const image=new Image();if(asset.src.startsWith('https:'))image.crossOrigin='anonymous';image.src=assetUrl(asset.src);
  image.decode().then(()=>{if(!active||!canvas.current)return;const scale=Math.min(1,2048/Math.max(image.naturalWidth,image.naturalHeight));const c=canvas.current;c.width=Math.round(image.naturalWidth*scale);c.height=Math.round(image.naturalHeight*scale);const context=c.getContext('2d',{willReadFrequently:true})!;context.drawImage(image,0,0,c.width,c.height);original.current=context.getImageData(0,0,c.width,c.height);setDimensions(`${c.width} × ${c.height}${scale<1?'（透明 PNG 最長邊 2048px）':''}`);setReady(true);}).catch(()=>setError('無法讀取圖片像素。外部圖片可能限制存取，請先下載後上傳原圖。'));return()=>{active=false;};
 },[asset.src]);
 useEffect(()=>{if(!original.current||!canvas.current||!ready)return;const data=original.current;const context=canvas.current.getContext('2d')!;if(!seed){context.putImageData(data,0,0);return;}const result=removeConnectedColor(data.data,data.width,data.height,seed,threshold,feather);context.putImageData(new ImageData(result.pixels,data.width,data.height),0,0);setColor(result.color);},[seed,threshold,feather,ready]);
 async function apply(){if(!canvas.current||!seed)return;setSaving(true);try{const c=canvas.current;const src=await uploadAsset(jobId,c.toDataURL('image/png'),asset.label+'-alpha.png');const id=crypto.randomUUID();onApply({...asset,id,src,label:asset.label+' / Alpha',width:c.width,height:c.height,kind:'uploaded',credit:asset.credit+'; color-key derivative'},{mode:'color-key',status:'ready',color,threshold,feather,resultAssetId:id});onClose();}catch(e){setError(e instanceof Error?e.message:'無法保存透明圖片。');}finally{setSaving(false);}}
 return <Dialog label="Instant Alpha 去背" onClose={saving?undefined:onClose} wide><span className="micro">IMAGE / INSTANT ALPHA</span><h2>點選想要移除的背景。</h2><p>調整容差與邊緣柔化。只處理點選處連續相近的顏色，原圖保留。</p><div className="alpha-workspace"><div className="alpha-canvas checkerboard"><canvas ref={canvas} aria-label="去背預覽，點選背景顏色" onClick={e=>{if(!ready||saving)return;const rect=e.currentTarget.getBoundingClientRect();setSeed({x:(e.clientX-rect.left)/rect.width*e.currentTarget.width,y:(e.clientY-rect.top)/rect.height*e.currentTarget.height});}}/></div><div className="alpha-controls"><label>背景色<span className="picked-color" style={{background:color}}/>{seed?color:'請在圖片上點選'}</label><label>容差 <output>{Math.round(threshold*100)}%</output><input aria-label="去背容差" type="range" min="0" max=".6" step=".01" value={threshold} disabled={saving} onChange={e=>setThreshold(Number(e.target.value))}/></label><label>邊緣柔化 <output>{Math.round(feather*100)}%</output><input aria-label="邊緣柔化" type="range" min="0" max=".2" step=".01" value={feather} disabled={saving} onChange={e=>setFeather(Number(e.target.value))}/></label><button className="subtle" disabled={saving} onClick={()=>setSeed(null)}>重設選取</button><p className="note">適合單色背景。複雜髮絲與相近膚色需要後續的 AI 去背工具。</p><small>{dimensions}</small><button className="start-project" disabled={!seed||saving} onClick={()=>void apply()}>{saving?'保存中…':browserOnly?'套用透明 PNG（瀏覽器示範）':'套用並保存透明 PNG'}</button>{error&&<p className="error" role="alert">{error}</p>}</div></div></Dialog>;
}
