import {getPack} from '../core/registry';
import type {MasterDocument} from '../core/schema';
import {ThemePicker} from './ThemePicker';
import { listJobs, loadJob } from '../app/storage';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useEditor } from '../app/useEditor';
import { validateDocument } from '../core/registry';
import { pageLabels } from '../core/actions';
import { layoutUnit } from '../engine/layout';
import { SvgPreview } from '../renderer/SvgPreview';
import { Inspector } from './Inspector';
import { downloadJson } from '../export/adapters';
import { ProjectComposer } from './ProjectComposer';
import { PageLibrary } from './PageLibrary';
import { Dialog } from './Dialog';
export default function App() {
 const editor=useEditor();const {doc,unit,slotId,pack}=editor;
 const [guides,setGuides]=useState(false),[zoom,setZoom]=useState(100),[notice,setNotice]=useState(''),[addOpen,setAddOpen]=useState(false),[themeOpen,setThemeOpen]=useState(!editor.started),[shelfOpen,setShelfOpen]=useState(false);
 const [planner,setPlanner]=useState<{themeId:string;initial?:MasterDocument}|null>(null);
 const [remoteJobs,setRemoteJobs]=useState<{id:string;title:string;units:number}[]>([]);
 useEffect(()=>{if(shelfOpen)void listJobs().then(setRemoteJobs).catch(()=>setNotice('無法連線工作資料夾；仍可開啟瀏覽器內的文件。'));},[shelfOpen]);
 const importRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{function shortcut(event:KeyboardEvent){if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='s'){event.preventDefault();if(editor.started&&!planner)void editor.saveNow();}}window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut);},[editor,planner]);
 const scene=useMemo(()=>layoutUnit(doc,unit,pack),[doc,unit,pack]);
 const thumbnails=useMemo(()=>doc.units.map(u=>layoutUnit(doc,u,pack)),[doc,pack]);
 const labels=pageLabels(doc),index=doc.units.findIndex(u=>u.id===unit.id);
 async function importFile(file?:File){if(!file)return;try{if(file.size>12000000)throw new Error('JSON 超過 12 MB。');const imported=validateDocument(JSON.parse(await file.text()));editor.commit(imported);editor.selectUnit(imported.units[0].id);setNotice('文件已匯入，可使用復原返回。');}catch(error){setNotice(error instanceof Error?error.message:'無法讀取文件。');}if(importRef.current)importRef.current.value='';}
 return <div className="app-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark">e<span>.</span></span><strong>EasyPage</strong><span className="prototype">STUDIO / M1</span></div><div className="document-name"><button disabled={!!planner} onClick={()=>setShelfOpen(true)} aria-label="我的文件">▤</button><input aria-label="目前文件名稱" disabled={!!planner} value={planner?(planner.initial?.title||'新工作 / 頁序規劃'):doc.title} onChange={e=>editor.commit({...doc,title:e.target.value})}/></div><div className="top-actions"><button disabled={!!planner} onClick={()=>setThemeOpen(true)}>＋ 新建文件</button><button title="復原" aria-label="復原" disabled={!!planner||!editor.canUndo} onClick={editor.undo}>↶</button><button title="重做" aria-label="重做" disabled={!!planner||!editor.canRedo} onClick={editor.redo}>↷</button><span className="divider"/><button disabled={!!planner} onClick={()=>void editor.saveNow()}>儲存文件</button><button disabled={!!planner} onClick={()=>importRef.current?.click()}>匯入</button><button className="primary" disabled={!!planner} onClick={()=>downloadJson(doc)}>下載 JSON <span>↗</span></button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={e=>void importFile(e.target.files?.[0])}/></div></header>
  <div className="workflow-bar"><span>Theme <b>{planner?getPack(planner.themeId).manifest.name:pack.manifest.name}</b></span><div><button aria-pressed={!!planner} onClick={()=>{if(!planner)setPlanner({themeId:doc.stylePackId,initial:structuredClone(doc)});}}>頁序規劃</button><button aria-pressed={!planner} disabled={!!planner} onClick={()=>editor.setSlotId(null)}>圖文編輯</button></div><small>{planner?'規劃完成後套用，即可繼續編輯':'可隨時調整頁序，圖文會保留'}</small></div>
  {planner?<ProjectComposer key={planner.initial?.id||planner.themeId} themeId={planner.themeId} initial={planner.initial} onCancel={()=>{setPlanner(null);if(!editor.started)setThemeOpen(true);}} onApply={next=>{if(planner.initial){editor.commit(next);editor.setSlotId(null);}else editor.openProject(next);setPlanner(null);}}/>:<div className="workspace">
   <aside className="pages-panel"><div className="style-selector"><span className="micro">YOUR STYLE PACK</span><button onClick={()=>setThemeOpen(true)}><span className="style-swatch"/><span>{pack.manifest.name}<small>瀏覽風格與頁型庫</small></span><span>⌄</span></button></div><div className="pages-heading"><span>頁面與跨頁</span><span>{doc.units.length} 單位</span></div>
    <nav className="page-list" aria-label="頁面與跨頁">{doc.units.map((page,i)=><button className={`page-card ${page.id===unit.id?'active':''}`} key={page.id} onClick={()=>editor.selectUnit(page.id)} aria-current={page.id===unit.id?'page':undefined}><div className="thumb"><SvgPreview scene={thumbnails[i]} small/>{page.kind==='spread'&&<span className="spread-seam"/>}</div><div className="page-caption"><b>{labels[i]}</b><span>{page.label}</span><span className="page-kind">{page.kind==='spread'?'LR':'S'}</span></div></button>)}</nav>
    <button className="add-page" onClick={()=>setAddOpen(true)}>＋ 新增頁面或跨頁</button>
   </aside>
   <main className="canvas-panel"><div className="canvas-toolbar"><div><span className="micro">{pack.manifest.name}</span><h1>{unit.label} <span>/ {labels[index]}</span></h1></div><div className="canvas-actions"><label className="guide-toggle"><input type="checkbox" checked={guides} onChange={e=>setGuides(e.target.checked)}/>中縫參考線</label><button title="往前移" aria-label="往前移" disabled={index===0} onClick={()=>editor.dispatch({type:'move-unit',unitId:unit.id,delta:-1})}>←</button><button title="往後移" aria-label="往後移" disabled={index===doc.units.length-1} onClick={()=>editor.dispatch({type:'move-unit',unitId:unit.id,delta:1})}>→</button><button title="複製目前頁面" aria-label="複製目前頁面" disabled={doc.units.length>=200} onClick={()=>{const id=crypto.randomUUID();editor.dispatch({type:'duplicate-unit',unitId:unit.id,id});editor.selectUnit(id);}}>⧉</button><button title="移除頁面（可復原）" aria-label="移除頁面" disabled={doc.units.length===1} onClick={()=>{editor.dispatch({type:'remove-unit',unitId:unit.id});editor.setSlotId(null);}}>−</button></div></div>
    <div className="canvas-scroll"><div className="canvas-artboard" style={{width:`${zoom}%`}}><div className="artboard-meta"><span>{unit.kind==='spread'?'DESIGNED SPREAD':'SINGLE PAGE'}</span><span>{scene.width} × {scene.height}</span></div><div className="paper"><SvgPreview scene={scene} selected={slotId} onSelect={editor.setSlotId} guides={guides}/></div><div className="artboard-bottom"><span>{unit.kind==='spread'?'LEFT PAGE  /  '+labels[index].split('–')[0]:doc.title}</span><span>{unit.kind==='spread'?'RIGHT PAGE  /  '+labels[index].split('–')[1]:pack.manifest.name}</span></div></div></div>
    {scene.warnings.length>0&&<div className="warnings" role="status">{scene.warnings.map((warning,i)=><p key={i}>△ {warning}</p>)}</div>}
    <div className="canvas-footer"><span><span className="dot"/>{editor.saveStatus}</span><span className="disk-status" role="status">{editor.diskStatus}</span><div className="zoom"><button aria-label="縮小" onClick={()=>setZoom(z=>Math.max(60,z-10))}>−</button><button onClick={()=>setZoom(100)}>{zoom}%</button><button aria-label="放大" onClick={()=>setZoom(z=>Math.min(180,z+10))}>＋</button></div></div>
   </main>
   <Inspector doc={doc} unit={unit} pack={pack} sample={editor.sample} slotId={slotId} select={editor.setSlotId} variant={variantId=>editor.dispatch({type:'variant',unitId:unit.id,variantId})} update={(slotId,content)=>editor.dispatch({type:'slot',unitId:unit.id,slotId,content})} remove={slotId=>editor.dispatch({type:'remove-slot',unitId:unit.id,slotId})} applyAlpha={(id,asset,operation)=>editor.applyAlpha(unit.id,id,asset,operation)} restore={id=>editor.dispatch({type:'restore-slot',unitId:unit.id,slotId:id})} assetUpdate={(id,asset)=>editor.updateAsset(unit.id,id,asset)}/>
  </div>}
  {notice&&<div className="toast" role="status"><span>{notice}</span><button aria-label="關閉提示" onClick={()=>setNotice('')}>×</button></div>}
  {addOpen&&<Dialog label="新增頁面" onClose={()=>setAddOpen(false)} wide><span className="micro">STYLE PAGE LIBRARY</span><h2>從同一風格，選一個新頁型。</h2><p>加入目前頁面之後；每種頁型都可重複使用，內容各自獨立。</p><PageLibrary pack={pack} disabled={doc.units.length>=200} onAdd={(layoutId,variantId)=>{const id=crypto.randomUUID();editor.dispatch({type:'add-unit',layoutId,variantId,id,afterId:unit.id});editor.selectUnit(id);setAddOpen(false);}}/></Dialog>}
  {themeOpen&&<ThemePicker onClose={editor.started||planner?()=>setThemeOpen(false):undefined} onChoose={themeId=>{setThemeOpen(false);setPlanner({themeId});}}/>}
  {shelfOpen&&<Dialog label="我的文件" onClose={()=>setShelfOpen(false)}><span className="micro">YOUR DOCUMENTS</span><h2>我的文件</h2><p>瀏覽器中的編輯版本與工作資料夾中的文件。檔案圖示代表伺服器已保存的工作。</p><div className="project-shelf">{Object.values({...editor.documents,[doc.id]:doc}).map(project=><button key={project.id} onClick={()=>{editor.openProject(project);setShelfOpen(false);}}><strong>{project.title||'未命名文件'}</strong><span>{project.units.length} 個單位{project.id===doc.id?' · 目前編輯中':''}</span></button>)}{remoteJobs.filter(job=>!editor.documents[job.id]&&job.id!==doc.id).map(job=><button key={job.id} onClick={()=>{void loadJob(job.id).then(saved=>{editor.openProject(saved);setShelfOpen(false);}).catch(error=>setNotice(error.message));}}><strong>▤ {job.title}</strong><span>{job.units} 個單位 · 工作資料夾</span></button>)}</div></Dialog>}
 </div>;
}
