import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
mkdirSync('docs/screenshots',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1512,height:982},deviceScaleFactor:1});
const page=await context.newPage();const errors=[];
page.on('pageerror',error=>errors.push(error.message));
page.setDefaultTimeout(10000);
try {
await page.goto('http://127.0.0.1:5173');
await page.getByRole('button',{name:'或開啟整份示範文件 →'}).click();
await page.getByRole('heading',{name:'品牌氛圍開場 / 01'}).waitFor();
await page.screenshot({path:'docs/screenshots/editor-cover.png'});
await page.getByRole('button',{name:'編輯 title',exact:true}).click();
await page.getByLabel('文字內容',{exact:true}).fill('A ritual, made yours.');
assert.equal(await page.getByRole('button',{name:'移除此選用欄位'}).count(),0);
await page.getByRole('button',{name:'返回版面設定'}).click();
await page.getByLabel('切換構圖').selectOption('reverse');
await page.getByRole('button',{name:'編輯 title',exact:true}).click();
assert.equal(await page.getByLabel('文字內容',{exact:true}).inputValue(),'A ritual, made yours.');
await page.getByRole('button',{name:'返回版面設定'}).click();
await page.getByRole('button',{name:'新增引言'}).click();
await page.getByLabel('文字內容',{exact:true}).fill('Designed for a slower day.');
await page.getByText('視覺效果',{exact:false}).click();
await page.getByLabel('透明度',{exact:true}).fill('0.7');
await page.getByRole('button',{name:'移除此選用欄位'}).click();
assert.equal(await page.getByRole('button',{name:'新增引言'}).count(),1);
await page.getByRole('button',{name:'編輯 hero',exact:true}).click();
await page.getByLabel('素材名稱',{exact:true}).fill('My NARA bottle');
await page.getByLabel('構圖',{exact:true}).selectOption('contain');
await page.getByLabel('裁切範圍').selectOption('inset');
await page.getByLabel('焦點 X',{exact:true}).fill('0.7');
await page.getByText('視覺效果',{exact:false}).click();
await page.getByLabel('模糊',{exact:true}).fill('2');
await page.getByLabel('染色強度',{exact:true}).fill('0.15');
await page.getByLabel('柔和陰影').check();
await page.getByText('已儲存至此瀏覽器',{exact:true}).waitFor();
const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('easypage.document.v0.1')));
assert.equal(stored.units[0].slots.title.text,'A ritual, made yours.');
assert.equal(stored.units[0].slots.hero.operations.crop.width,.7);
assert.equal(stored.units[0].slots.hero.operations.focal.x,.7);
assert.equal(stored.assets[stored.units[0].slots.hero.assetId].label,'My NARA bottle');
assert.equal(stored.assets[stored.units[3].slots.hero.assetId].label,'NARA / Daily Botanical Serum');
await page.reload();
await page.getByRole('button',{name:'編輯 title',exact:true}).click();
assert.equal(await page.getByLabel('文字內容',{exact:true}).inputValue(),'A ritual, made yours.');
await page.getByRole('button',{name:/12–13 影像故事 LR/}).click();
await page.getByLabel('中縫參考線').check();
await page.screenshot({path:'docs/screenshots/editor-spread.png'});
await page.getByRole('button',{name:'新增頁面或跨頁'}).click();
await page.getByRole('dialog').getByRole('button',{name:'加入主打產品'}).click();
assert.equal(await page.locator('nav.page-list > button').count(),10);
await page.getByRole('button',{name:'復原',exact:true}).click();
assert.equal(await page.locator('nav.page-list > button').count(),9);
await page.getByRole('button',{name:'重做',exact:true}).click();
assert.equal(await page.locator('nav.page-list > button').count(),10);
const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:/下載 JSON/}).click();const download=await downloaded;
const stream=await download.createReadStream();const chunks=[];for await(const chunk of stream)chunks.push(chunk);const exported=JSON.parse(Buffer.concat(chunks).toString());assert.equal(exported.units.length,10);
await page.locator('input[accept="application/json,.json"]').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(stored))});
await page.getByText('文件已匯入，可使用復原返回。').waitFor();assert.equal(await page.locator('nav.page-list > button').count(),9);
assert.deepEqual(errors,[]);
console.log('Browser checks passed: edit, variant preservation, required protection, optional reflow, image metadata, crop/focal/effects, autosave, add, undo/redo, JSON export/import.');
} catch(error) { await page.screenshot({path:'docs/screenshots/check-failure.png'}); throw error; } finally { await browser.close(); }
