import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1512,height:982}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:5173');
 const composer=page.getByRole('dialog',{name:'建立自己的文件'});await composer.waitFor();
 assert.equal(await composer.getByRole('button',{name:'開始放入圖文 ↗'}).isEnabled(),false);
 await composer.getByLabel('文件名稱',{exact:true}).fill('My personal catalog');
 for(const name of ['品牌氛圍開場','主打產品','主打產品','品牌人物','結語與邀請'])await composer.getByRole('button',{name:`加入${name}`,exact:true}).click();
 await composer.getByRole('button',{name:'重複第 3 個單位',exact:true}).click();
 await composer.getByRole('button',{name:'移除第 4 個單位',exact:true}).click();
 await composer.getByRole('button',{name:'往前移第 4 個單位',exact:true}).click();
 await page.screenshot({path:'docs/screenshots/page-composer.png'});
 await composer.getByRole('button',{name:'開始放入圖文 ↗'}).click();
 assert.equal(await page.locator('nav.page-list > button').count(),5);
 assert.equal(await page.getByLabel('目前文件名稱').inputValue(),'My personal catalog');
 await page.getByRole('button',{name:/03–04 品牌人物 LR/}).click();
 await page.getByRole('button',{name:'編輯 hero',exact:true}).waitFor();await page.getByRole('button',{name:'編輯 secondary',exact:true}).waitFor();
 await page.screenshot({path:'docs/screenshots/team-independent-portraits.png'});
 await page.getByRole('button',{name:'編輯 hero',exact:true}).click();
 await page.locator('input[type=file][accept="image/png,image/jpeg,image/webp"]').setInputFiles('public/assets/nara-serum.png');
 await page.getByLabel('素材名稱',{exact:true}).fill('Individual portrait one');
 await page.getByLabel('焦點 X',{exact:true}).fill('0.25');
 await page.getByRole('button',{name:'編輯 secondary',exact:true}).click();
 assert.equal(await page.getByLabel('素材名稱',{exact:true}).inputValue(),'Alex / portrait placeholder');
 assert.equal(await page.getByLabel('焦點 X',{exact:true}).inputValue(),'0.5');
 await page.getByRole('button',{name:'返回版面設定'}).click();await page.getByLabel('切換構圖').selectOption('reverse');
 await page.getByRole('button',{name:'編輯 hero',exact:true}).click();assert.equal(await page.getByLabel('素材名稱',{exact:true}).inputValue(),'Individual portrait one');
 await page.getByRole('button',{name:'複製目前頁面'}).click();assert.equal(await page.locator('nav.page-list > button').count(),6);
 await page.getByText('已儲存至此瀏覽器',{exact:true}).waitFor();
 await page.getByRole('button',{name:'＋ 新建文件'}).click();
 await page.getByRole('dialog').getByLabel('文件名稱',{exact:true}).fill('Second catalog');
 await page.getByRole('dialog').getByRole('button',{name:'加入結語與邀請'}).click();await page.getByRole('button',{name:'開始放入圖文 ↗'}).click();
 assert.equal(await page.locator('nav.page-list > button').count(),1);
 await page.getByText('已儲存至此瀏覽器',{exact:true}).waitFor();await page.reload();
 assert.equal(await page.getByLabel('目前文件名稱').inputValue(),'Second catalog');
 await page.getByRole('button',{name:'我的文件',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:/My personal catalog/}).click();
 assert.equal(await page.locator('nav.page-list > button').count(),6);
 assert.equal(await page.getByLabel('目前文件名稱').inputValue(),'My personal catalog');
 assert.deepEqual(errors,[]);console.log('Passed: custom pagination, repeated templates, reorder/remove, independent portrait upload and focal, variant preservation, duplicate, multiple projects, reload and switching.');
}catch(e){await page.screenshot({path:'docs/screenshots/workflow-failure.png'});throw e;}finally{await browser.close();}
